In [1]:
#creating 1d array
import numpy as np
arr = np.array([1,2,3,4])
print (arr)

[1 2 3 4]


In [13]:
#create 2d array with 6 rows and 5 column
import numpy as np
array = np.arange(30).reshape(6,5)
print (array)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


In [29]:
#fill the 2d array with zeros and one 
import numpy as np
x = np.zeros((5,4))
x


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [31]:
#fill 2d array with ones 
import numpy as np
y = np.ones((3,6))
y

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [33]:
#create a full function with 2d ,filler of 7
z = np.full((4,5),7)
z

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [41]:
#implementing a function to find out the dimension of given array
import numpy as np
a = np.array ([1,2])
b = np. array ([[1,1,1],[2,2,2]])
print (a.ndim)
print (b.ndim)


1
2


In [45]:
#creating 8d array with value (2,2,2,2)
import numpy as np
x = np.array([2,2,2,2],ndmin = 8)
x

array([[[[[[[[2, 2, 2, 2]]]]]]]])

In [49]:
import numpy as np
arr=np.identity(6)
print(arr)
print(arr[:,:])
print(arr[2:5,0:3])

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
[[0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]
